### ISSUE TITLE
Some errors about highway_env

### ISSUE THREAD

**Issue by ispencerlee** [FanGShiYuu/CoDrivingLLM#4]
## Thanks for your nice job.
but when I'm running the code 
```python Run_multi_CAV_LLM.py```
## My environment:
code was depends on  the commit of 4 days ago
python 3.10

requirments.txt:
```
numpy
openai==1.2.2
gym==0.15.3
matplotlib
pandas
pygame
# langchain==0.0.335
langchain-community==0.3.5
imageio
imageio-ffmpeg
openpyxl
highway-env
chromadb==0.4.15
sentence-transformers==3.0.1
tiktoken

```
# I got those errors
### errors:
```
(venv) ☁  CoDrivingLLM [master] ⚡  py Run_multi_CAV_LLM.py
Traceback (most recent call last):
  File "/home/spencer/CoDrivingLLM/Run_multi_CAV_LLM.py", line 85, in <module>
    obs, global_reward, terminated, info = env.step(tuple(action), env)
  File "/home/spencer/CoDrivingLLM/highway_env/envs/intersection_env.py", line 123, in step
    obs, reward, done, info = super().step(action, env)
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/abstract.py", line 472, in step
    self._simulate(self.new_action)
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/abstract.py", line 527, in _simulate
    self.action_type.act(action)  # defined in action.py
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/action.py", line 250, in act
    action_type.act(agent_action)
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/action.py", line 219, in act
    self.controlled_vehicle.act(self.actions[action])
KeyError: -1
```
I got this error when I'm running about 2 rounds, and got a video only 1 second,
I look up the code but I don't know how fix it

### errors:
```

(venv) ☁  CoDrivingLLM [master] ⚡  py Run_multi_CAV_LLM.py
/home/spencer/CoDrivingLLM/llm_controller/memory.py:2: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import Chroma

with new imports of:

>> from langchain_community.vectorstores import Chroma
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/docs/versions/v0_2/>
  from langchain.vectorstores import Chroma
/home/spencer/CoDrivingLLM/highway_env/envs/common/observation.py:219: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame(data=rows, columns=self.features), ignore_index=True)
/home/spencer/CoDrivingLLM/highway_env/envs/common/observation.py:219: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame(data=rows, columns=self.features), ignore_index=True)
---------------------------------------------------------------
/home/spencer/CoDrivingLLM/llm_controller/memory.py:14: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-openai package and should be used instead. To use it run `pip install -U :class:`~langchain-openai` and import as `from :class:`~langchain_openai import OpenAIEmbeddings``.
  self.embedding = OpenAIEmbeddings()
/home/spencer/CoDrivingLLM/llm_controller/memory.py:16: LangChainDeprecationWarning: The class `Chroma` was deprecated in LangChain 0.2.9 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-chroma package and should be used instead. To use it run `pip install -U :class:`~langchain-chroma` and import as `from :class:`~langchain_chroma import Chroma``.
  self.scenario_memory = Chroma(
==========Loaded  ./db/highway-v0  Memory, Now the database has  0  items.==========
Traceback (most recent call last):
  File "/home/spencer/CoDrivingLLM/Run_multi_CAV_LLM.py", line 72, in <module>
    negotiation_prompt, conflicting_info = llm_agent_conflict_resolver.llm_controller_run(env)
  File "/home/spencer/CoDrivingLLM/llm_controller/llm_agent_negotiation_system.py", line 26, in llm_controller_run
    conflict = self.detect_conflicts(env)
  File "/home/spencer/CoDrivingLLM/llm_controller/llm_agent_negotiation_system.py", line 56, in detect_conflicts
    is_conflicts, distance_to_conflict_point = self.is_conflict(env, vehicle_i, vehicle_j)
  File "/home/spencer/CoDrivingLLM/llm_controller/llm_agent_negotiation_system.py", line 65, in is_conflict
    route_i = self.record_route_xy(env, vehicle_i)
  File "/home/spencer/CoDrivingLLM/llm_controller/llm_agent_negotiation_system.py", line 131, in record_route_xy
    for lane_index in vehicle.route:
TypeError: 'NoneType' object is not iterable
```
I have no idea, how to fix it
## merge_env
```
(venv) ☁  CoDrivingLLM [master] ⚡  py Run_multi_CAV_LLM.py
/home/spencer/CoDrivingLLM/llm_controller/memory.py:2: LangChainDeprecationWarning: Importing Chroma from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import Chroma

with new imports of:

>> from langchain_community.vectorstores import Chroma
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/docs/versions/v0_2/>
  from langchain.vectorstores import Chroma
Traceback (most recent call last):
  File "/home/spencer/CoDrivingLLM/Run_multi_CAV_LLM.py", line 55, in <module>
    env = gym.make('highway-v0')
  File "/home/spencer/CoDrivingLLM/venv/lib/python3.10/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/spencer/CoDrivingLLM/venv/lib/python3.10/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/spencer/CoDrivingLLM/venv/lib/python3.10/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/abstract.py", line 87, in __init__
    self.reset()
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/abstract.py", line 200, in reset
    obs = self.observation_type.observe()
  File "/home/spencer/CoDrivingLLM/highway_env/envs/common/observation.py", line 219, in observe
    df = df.append(pd.DataFrame(data=rows, columns=self.features), ignore_index=True)
  File "/home/spencer/CoDrivingLLM/venv/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```
this warning can be solved by doing this: 
```
pip install langchain-community
```

In *memory.py*
```
# from langchain.embeddings.openai import OpenAIEmbeddings
# from langchain.docstore.document import Document
from langchain_community.embeddings import OpenAIEmbeddings
from langchain_community.vectorstores import Chroma
```
I found it was because pandas removed [ append ](https://stackoverflow.com/questions/75956209/error-dataframe-object-has-no-attribute-append) method while *pandas 2.0*, 
my pands version is 
```
(venv) ☁  CoDrivingLLM [master] ⚡  pip list | grep pandas
pandas                                   2.2.3
```
when I degrade it's version to [1.5.3](https://pypi.org/project/pandas/1.5.3/), it works fun.

**Comment by FanGShiYuu** [comment]
Thank you for your detailed explanation! Here are our responses to the issues raised:  

1. **Regarding the `KeyError: -1` issue in `intersection_env`:**  
   This error occurs because the LLM generated an action that wasn’t part of the available actions (e.g., `faster` with lowercase). To resolve this, please ensure that the LLM outputs actions matching the expected format exactly.  

2. **Regarding the `TypeError: 'NoneType' object is not iterable` in `highway_env`:**  
   The root cause is that the memory database currently has no data, as indicated by the message:  
========== Loaded ./db/highway-v0 Memory, Now the database has 0 items ==========
Without data in the memory, the retrieval process cannot proceed. To fix this, during the pre-training phase, uncomment line 46 in `llm_controller/llm_agent_action.py` to enable adding memories to the database.  

3. **Regarding the pandas version compatibility:**  
Thank you for pointing this out! The issue is indeed related to the pandas version. We’ve updated the requirements file to specify `pandas==1.3.5`, which resolved the problem on our side.  

If you have any further questions or need assistance, feel free to let us know! 😊
